[package]
name = "functions_assignment"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]
name = "functions_assignment"
function = "functions_assignment::functions::main"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = ">=2.18.0"